config/routes.rb
Rails.application.routes.draw do
  root to: 'monologues#index'
  resources :monologues do
    post :confirm, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monologue.rb
class Monologue < ApplicationRecord
    validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/monologues_controller.rb
class MonologuesController < ApplicationController
    before_action :set_monologue, only: [:destroy, :edit, :update]
    def index
        @monologues = Monologue.all
    end
    def edit
    end
    def update
        if @monologue.update(monologue_params)
            redirect_to monologues_path, notice: '編集に成功しました!'
        else
            render 'edit'
        end
    end
    def create
        @monologue = Monologue.new(monologue_params)
        if @monologue.save
            redirect_to monologues_path, notice: 'ささやけました!'
        else
            render 'new'
        end
    end
    def new
        if params["back"]
            @monologue = Monologue.new(monologue_params)
        else
            @monologue = Monologue.new
        end
    end
    def confirm
        @monologue = Monologue.new(monologue_params)
        render 'new' if @monologue.invalid?
    end
    def destroy
        if @monologue.destroy
            redirect_to monologues_path, notice: '削除に成功しました'
        end
    end
    private
    def set_monologue
        @monologue = Monologue.find(params[:id])
    end
    def monologue_params
        params.require(:monologue).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monologues_helper.rb
module MonologuesHelper
# _form.html.erb送信先(url:)のpathをactionによって切り替える
    def new_or_edit_path
        if action_name == "new" || action_name == "confirm"
            confirm_monologues_path
        elsif action_name == "edit"
            monologue_path
        end
    end
# _form.html.erbのsubmitボタンの名前をactionによって切り替える
    def new_or_edit_submit_message
        if action_name == "new" || action_name == "confirm"
            "ささやく"
        elsif action_name == "edit"
            "Edit"
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whisper</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://whisper-sacrament.c9users.io/monologues">WHISPER</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="https://whisper-sacrament.c9users.io/monologues">TOP</a></li>
        <li><a href="https://whisper-sacrament.c9users.io/monologues/new">ささやく</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>
  <%= yield %>
<footer class="footer">
</footer>
</body>
</html>

app/views/monologues/_form.html.erb
<%= form_with model: @monologue, local: true, url: new_or_edit_path do |form| %>
<% if @monologue.errors.any? %>
	<ul class="error-list">
		<% @monologue.errors.full_messages.each do |msg| %>
			<li class="alert alert-danger col-xs-offset-1 col-xs-9"><%= msg %></li>
		<% end %>
	</ul>
<% end %>

		<%= form.label :content, "comment:", class: 'col-xs-offset-2 col-xs-12 text-left form-label' %>
		<%= form.text_area :content, size: '80×5', class: 'col-xs-8 col-xs-offset-2 form-texarea' %>
	<%= form.submit new_or_edit_submit_message, class: 'btn btn-warning  col-xs-offset-3 col-xs-6 form-submit-btn' %>
<% end %>

app/views/monologues/confirm.html.erb
<h2 class="col-xs-12 text-center confirm-text">以下の内容でささやきますか?</h2>
<%= form_with model: @monologue, url: monologues_path, local: true do |form| %>
  <%= form.hidden_field :content %>
  
<div class="panel panel-default col-xs-10 col-xs-offset-1">
  <div class="panel-body">
    <%= simple_format @monologue.content %>
  </div>
</div>
  <%= form.submit  "ささやく", class: 'btn btn-warning col-xs-6 confirm-submit-btn' %>
<% end %>

<%= form_with model: @monologue, url: new_monologue_path, local: true, method: 'get' do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit  "もどる", name: 'back', class: 'btn btn-danger col-xs-offset-3 col-xs-6' %>
<% end %>

app/views/monologues/edit.html.erb
<h2 class="col-xs-12 text-center edit-text">ささやきを編集します</h2>
<%= render 'form' %>

app/views/monologues/index.html.erb
<% if notice %>
  <div class="col-xs-10 col-xs-offset-1 alert alert-success"><%= notice %></div>
<% end %>

<% @monologues.each do |m| %>
  <div class="panel panel-default col-xs-10 col-xs-offset-1">
    <div class="panel-body">
      <%= simple_format m.content %>
    </div>
    <div class="edit-btn">
      <%= link_to 'Edit', edit_monologue_path(m.id), class: 'btn btn-success' %>
    </div>
    <div class="delete-btn">
      <%= link_to 'Delete', monologue_path(m.id), method: :delete, data: { confirm: '本当にささやきを消しますか?' }, class: 'btn btn-danger' %>
    </div>
  </div>
<%end%>

<div><%= link_to 'ささやく', new_monologue_path, class: 'sasakasu-btn btn btn-warning col-xs-offset-3 col-xs-6' %></div>

app/views/monologues/new.html.erb
<h2 class="col-xs-12 text-center new-text">なにかつぶやいてみよう!</h2>
<a class="col-xs-12 text-center new-text">1〜140字以内で入力してください</a>
<%= render 'form' %>